{% set version = '0.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dbi
  version: {{ version|replace("-", "_") }}

source:
  fn: DBI_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/DBI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DBI/DBI_{{ version }}.tar.gz
  sha256: d52b9e04b3291f9bda8a88c174678f520ddffc5f2edf9b3dfa6d97dca943ce9a

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: blob, covr, hms, knitr, magrittr, rprojroot, rmarkdown, RSQLite (>= 1.1-2), testthat, xml2
requirements:
  build:

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('DBI')"           # [not win]
    - "\"%R%\" -e \"library('DBI')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://r-dbi.github.io/DBI
  license: LGPL (>= 2)
  summary: A database interface definition for communication between R and relational database
    management systems.  All classes in this package are virtual and need to be extended
    by the various R/DBMS implementations.
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: DBI
# Version: 0.8
# Date: 2018-02-24
# Title: R Database Interface
# Description: A database interface definition for communication between R and relational database management systems.  All classes in this package are virtual and need to be extended by the various R/DBMS implementations.
# Authors@R: c( person("R Special Interest Group on Databases (R-SIG-DB)", role = "aut"), person("Hadley", "Wickham", role = "aut"), person("Kirill", "Muller", email = "krlmlr+r@mailbox.org", role = c("aut", "cre")) )
# Depends: R (>= 3.0.0), methods
# Suggests: blob, covr, hms, knitr, magrittr, rprojroot, rmarkdown, RSQLite (>= 1.1-2), testthat, xml2
# Encoding: UTF-8
# License: LGPL (>= 2)
# URL: http://r-dbi.github.io/DBI
# URLNote: https://github.com/r-dbi/DBI
# BugReports: https://github.com/r-dbi/DBI/issues
# Collate: 'DBObject.R' 'DBDriver.R' 'table.R' 'DBConnection.R' 'ANSI.R' 'DBI-package.R' 'DBResult.R' 'data-types.R' 'data.R' 'deprecated.R' 'hidden.R' 'interpolate.R' 'list-pairs.R' 'quote.R' 'rd.R' 'rownames.R' 'table-create.R' 'table-insert.R' 'transactions.R'
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-02-27 06:10:56 UTC; muelleki
# Author: R Special Interest Group on Databases (R-SIG-DB) [aut], Hadley Wickham [aut], Kirill Muller [aut, cre]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2018-03-02 16:44:44 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
