# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qtgFDC0nzJtm6Jy8xQPYj4VHlJGD8m/TpFo6XaRWauBojl0EVWt4XYs3LRZLWcr6wsnAJQwH9hpK9pUs2pEiF/0kovN79CZElVf1Sn1WTfHz9BwYbGm5qd29oCHpVPIX2rAMIphgHtNyyYnV/2WVDoR510NJ7uqUmE1hUrCv5wg9ZWUnggosY0WRqIlsw4gIZ5hX6EFKDhKcewg/riQ6cHDkfpRHVjdULrB5iO7jtvn8bCxgMJaRMciwAIDuWNC+6GENJ6BR/Q8Oi+fa39IufYc0b/W1IJorlIWW0riYdUgnd+T5w/wWFp3OXPw4QZZ7B38OC6s0ylt2KhOIw3aVMUJSMt9ms7zqZSuu7MWU7IMWLYncEbW8dCdlqpn8jqlacGvk3nlENxE9XuS81hRE6prmEyP0HHr4XARZGYgqFuq0lfMR6V3pE7MJsVQH9n62iSILYUz55IBQ40zDNGDq1+EUwOFw0lQtMuVhgxo1ppjHwAUeXC3mP+eJ5r7kreyKll1PjpJFdB0hIMqkoV+0tfQQ2dP1eM2YLAl08oLS+9HV62p8est3rX8imO64xStWDEZ4NhzdvryOZ1fQ9MYsScbZ0MvLftUOrBShtGCN3c9t7/wtcAoHoyCIHCTv6GCVqw/tcHs45rCA6o3Fo4Sy+/JuCb4b28sKHLvCJb3YdXA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
