travis:
  secure:
    BINSTAR_TOKEN: iyM5HP+MG4p5i9N60yu08HEAm/FoO4i9Swt7Tvdu4zM2HWYs0uZnV5N6XR8H8NJNdfAvMIephV5rDQFzORtvi8GL44RQcVTXKohw9t+aAsBQwEZNmfWTuN0eOsgh8UjhAiRYINPuIzqGgB8V2SGqgGZC0gTFwulEIK3NbLx491K4qL1hupe7AKQ1uA4+pfk2ZREm+0qqQYCowvGTEvuNKj0HB/GKO+FftVTnJuLlnLLzVZSmtbbBMLmWndanuLEEaeQ6vLhhDHJzoF3i9tUyvDSCiLEiK10pit+JYxFX3uV5qoaxIpr9mkQt4y4kVbS6rde6y1cxRfGLErFUzpGdGBtNXm5ZA1fDxszYV6ryGcUOrto5OrOdAxt4PyBTHyXdbgz2K1NQh/Yzn0j4mywaZCgD/0CJ75oWeA9e39SJrDzCq+ughkEKJCXtM9Yo86nXY45lTsOuqsnnGgRAy5DRYrdFn0n9PIcofosZvO4t0vNuEipCDItespZSbDORwABhGa7ylXxCXQuTn+CinRT5Amf3G6zpqRYCnRjI+KaVuQWI5R383dXayvlGGVE52f2bjaRBD2bDXGhlTrKq6Oao1lvNKHsIOXrLipVJ2El1c/d1zlO1RLk7Nh8pf+rMQ4By3QxUO0Lj1wqfyG7qJZMf11+R5lgzC5JQJ0uzzpVe6dI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
