travis:
  secure:
    BINSTAR_TOKEN: qtgFDC0nzJtm6Jy8xQPYj4VHlJGD8m/TpFo6XaRWauBojl0EVWt4XYs3LRZLWcr6wsnAJQwH9hpK9pUs2pEiF/0kovN79CZElVf1Sn1WTfHz9BwYbGm5qd29oCHpVPIX2rAMIphgHtNyyYnV/2WVDoR510NJ7uqUmE1hUrCv5wg9ZWUnggosY0WRqIlsw4gIZ5hX6EFKDhKcewg/riQ6cHDkfpRHVjdULrB5iO7jtvn8bCxgMJaRMciwAIDuWNC+6GENJ6BR/Q8Oi+fa39IufYc0b/W1IJorlIWW0riYdUgnd+T5w/wWFp3OXPw4QZZ7B38OC6s0ylt2KhOIw3aVMUJSMt9ms7zqZSuu7MWU7IMWLYncEbW8dCdlqpn8jqlacGvk3nlENxE9XuS81hRE6prmEyP0HHr4XARZGYgqFuq0lfMR6V3pE7MJsVQH9n62iSILYUz55IBQ40zDNGDq1+EUwOFw0lQtMuVhgxo1ppjHwAUeXC3mP+eJ5r7kreyKll1PjpJFdB0hIMqkoV+0tfQQ2dP1eM2YLAl08oLS+9HV62p8est3rX8imO64xStWDEZ4NhzdvryOZ1fQ9MYsScbZ0MvLftUOrBShtGCN3c9t7/wtcAoHoyCIHCTv6GCVqw/tcHs45rCA6o3Fo4Sy+/JuCb4b28sKHLvCJb3YdXA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
